spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
#日志级别配置
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG        #Spring框架中的日志级别
    com.javainuse.swaggertest: DEBUG    #自己项目包名下的日志级别
#    org:  DEBUG   #输出org包下的日志
  file:
    max-size: 1MB
    max-history: 5
  path: @log.path@
  pattern:
    dateformat: yyyy/MM/dd HH-mm-ss
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
entitymanager:
  packagesToScan: com.javainuse.swaggertest.entity





